In [1]:
import numpy as np

In [4]:
A = np.arange(1,10).reshape(3,3)
print(A)
B = np.full((3,3),fill_value=3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [7]:
C= A.dot(B)
print(C)

[[18 18 18]
 [45 45 45]
 [72 72 72]]


In [8]:
C= B.dot(A)
print(C)

[[36 45 54]
 [36 45 54]
 [36 45 54]]


In [10]:
C = A+B
print(A.T+B.T)
print(C.T)

[[ 4  7 10]
 [ 5  8 11]
 [ 6  9 12]]
[[ 4  7 10]
 [ 5  8 11]
 [ 6  9 12]]
