In [1]:
import numpy as np
import math

In [2]:
def computeVectorLength(vector):
    sum_vector = np.sum(vector*vector)
    len_of_vector = math.sqrt(sum_vector)
    return len_of_vector
vector = np.array([-2, 4, 9, 21])
result = computeVectorLength(vector)
print(round(result,2))

23.28


In [3]:
def computeDotProduct(vector1, vector2):
    result = vector1.dot(vector2.T)
    return result

v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = computeDotProduct(v1, v2)
print(round(result,2))

4


In [4]:
x = np.array([[1, 2],
[3, 4]])
print(x)
k = np.array([1, 2])
print(k)
print('result \n', x.dot(k))

[[1 2]
 [3 4]]
[1 2]
result 
 [ 5 11]


In [5]:
x = np.array([[-1, 2],
              [3, -4]])
k = np.array([1, 2])
print('result \n', x@k)

result 
 [ 3 -5]


In [6]:
def matrix_multi_vector(matrix, vector):
    result = matrix.dot(vector)
    return result

In [7]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
# result = m.dot(v)
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [8]:
def matrix_multi_matrix(matrix1,matrix2):
    len_of_vector = matrix1.dot(matrix2)
    return len_of_vector
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3],[6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [9]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1],[2, 2, 2], [3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [10]:
m1 = np.eye(2)
print(m1)
m1 = np.reshape(m1,(-1,4))[0]
print(m1)
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
print(m2)
result = m1@m2
print(result)

[[1. 0.]
 [0. 1.]]
[1. 0. 0. 1.]
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
[5. 5. 5. 5.]


In [12]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1,(-1,4), "F")[0]
print(m1)
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[1 3 2 4]
[29 29 29 29]


In [13]:
def inverse_matrix(matrix):
    print(matrix)
    det = matrix[0,0]*matrix[1,1] - matrix[0,1]*matrix[1,0]
    matrix[0,0], matrix[1,1] = matrix[1,1], matrix[0,0]
    matrix[1,0] = -matrix[1,0]
    matrix[0,1] = -matrix[0,1]
    print(matrix)
    if det !=0 :
        result = (1/det)*matrix
    else :
        result = None
        print('det(matrix) = 0 ')
    return result
m1 = np.array([[-2, 6], [8, -4]])
# m1[0,0], m1[1,1] = -m1[1,1], -m1[0,0]
# print(m1)
result = inverse_matrix(m1)
print(result)

[[-2  6]
 [ 8 -4]]
[[-4 -6]
 [-8 -2]]
[[0.1  0.15]
 [0.2  0.05]]


# Eigenvector and eigenvalues
> A.v=lamba.v <=>  A.v-lamba.v =0  
> A.v-lamba.I.v =0 <=> v(A-lamba.I)=0 
> với v !=0 ta có : det(A-lamba.I)=0




In [4]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalue, eigenvectors = np.linalg.eig(matrix)
    return eigenvalue, eigenvectors
# matrix = np.array([[-6, 3], [4, 5]])
# matrix2 = np.array([6,6])
# print(matrix.T.dot(matrix2))
# # print(matrix)
# # print(compute_eigenvalues_eigenvectors(matrix))
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
math.gcd()

In [27]:
def compute_cosine(v1, v2):
    sum_xy = sum( x1*x2 for x1,x2 in zip(v1,v2) )
    sum_xx = sum(x*x for x in v1)
    sum_yy = sum(y*y for y in v2)
    cos_sim = sum_xy/(math.sqrt(sum_xx)+math.sqrt(sum_yy))
    return cos_sim
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

1.157
